imports:
  - { resource: ../../_shared/config/services.yaml }

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Admin\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/AdminKernel.php'
